const DEFAULT={xp:0,streak:0,last:'',done:{},rev:[],seen:{},aiBank:{},aiCount:0};
let S=loadState(),ses=null,M=document.getElementById('m'),deferredInstall=null,aiConfigured=null;
function loadState(){try{const x=JSON.parse(localStorage.getItem('gl-v2')||'null')||JSON.parse(localStorage.getItem('gl')||'null')||{};return {...DEFAULT,...x,done:x.done||{},rev:x.rev||[],seen:x.seen||{},aiBank:x.aiBank||{}}}catch{return structuredClone(DEFAULT)}}
function save(){try{localStorage.setItem('gl-v2',JSON.stringify(S))}catch{}}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function today(){return new Date().toLocaleDateString('sv-SE')}
function addXp(n){const d=today();if(S.last!==d){S.streak=S.last&&((new Date(d)-new Date(S.last))/864e5===1)?S.streak+1:1;S.last=d}S.xp+=n;save()}
function mastery(id){return Math.min(100,(S.done[id]||0)*25)}
function due(){return S.rev.filter(r=>r.n<=Date.now())}
function topic(id){return TOPICS.find(x=>x.id===id)}
const REVIEW_INTERVALS=[20*60e3,1*864e5,3*864e5,7*864e5,14*864e5,30*864e5,60*864e5];
const REVIEW_LABELS=['20分','1日','3日','7日','14日','30日','60日'];
function reviewStage(r){const raw=Number.isFinite(r.stage)?r.stage:(Number.isFinite(r.s)?r.s:0);return Math.max(0,Math.min(REVIEW_INTERVALS.length-1,raw))}
function scheduleLabel(stage){return REVIEW_LABELS[Math.max(0,Math.min(REVIEW_LABELS.length-1,stage))]}
function addReview(t,p,a,result='new'){const k=t.id+'|'+p;let r=S.rev.find(q=>q.k===k);if(!r){r={k,id:t.id,p,a,stage:0,s:0,n:Date.now()};S.rev.push(r)}r.p=p;r.a=a;let stage=reviewStage(r);if(result===true||result==='good')stage=Math.min(REVIEW_INTERVALS.length-1,stage+1);else if(result===false||result==='bad')stage=0;r.stage=stage;r.s=stage;r.n=Date.now()+REVIEW_INTERVALS[stage];r.lastResult=result;r.updatedAt=Date.now();save();return r}
function header(title,sub){return `<div class="head"><div><h1>${esc(title)}</h1><p>${esc(sub)}</p></div><div class="pill">🔥 ${S.streak}日 ・ ${S.xp} XP</div></div>`}
function topicCard(t){return `<div class="card topic"><div class="ico">${t.icon}</div><div><h3>${esc(t.name)}</h3><p>${esc(t.rule)}</p><div class="bar"><i style="width:${mastery(t.id)}%"></i></div></div><button class="btn ghost" data-start="${t.id}">学習する</button></div>`}
function isStandalone(){return matchMedia('(display-mode: standalone)').matches||navigator.standalone===true}
function isIOS(){return /iphone|ipad|ipod/i.test(navigator.userAgent)}
function installCard(){if(isStandalone())return `<div class="card install"><h3>✅ アプリとして起動中</h3><p>GrammarLoopはホーム画面から独立したアプリとして使えます。</p></div>`;return `<div class="card install"><h3>📲 GrammarLoopをアプリにする</h3><p>${isIOS()?'Safariの共有ボタン →「ホーム画面に追加」でインストールできます。':'対応ブラウザなら下のボタンからインストールできます。出ない場合はブラウザメニューの「アプリをインストール」または「ホーム画面に追加」を使ってください。'}</p><button class="btn primary" data-install>${deferredInstall?'アプリをインストール':'インストール方法を表示'}</button></div>`}
function go(v){document.querySelectorAll('[data-v]').forEach(b=>b.classList.toggle('on',b.dataset.v===v));if(v==='home')home();if(v==='topics')topics();if(v==='review')review();if(v==='stats')stats();scrollTo(0,0)}
function home(){const aiSaved=Object.values(S.aiBank).reduce((n,a)=>n+(a?.length||0),0);M.innerHTML=header('英文法を「読める・使える」に','理解 → 4択 → 英作文 → 短文読解 → 忘却曲線ベース復習')+`<div class="grid g3"><div class="card stat"><small>XP</small><b>${S.xp}</b></div><div class="card stat"><small>復習待ち</small><b>${due().length}</b></div><div class="card stat"><small>保存済みAI短文</small><b>${aiSaved}</b></div></div><div class="card hero"><h2>今日の15〜25分</h2><p>ルール暗記だけで終わらず、文章の中で意味が取れるところまで練習します。短文は複数候補から出題し、読み切った時だけAIで新しい1本を追加します。</p><button class="btn primary" data-rec>今日の学習を始める</button><div id="ai-status" style="margin-top:10px;color:#d1d5db;font-size:13px">AI接続を確認中…</div></div><div style="margin-top:13px">${installCard()}</div><h2>おすすめ</h2><div class="grid topics">${[...TOPICS].sort((a,b)=>mastery(a.id)-mastery(b.id)).slice(0,4).map(topicCard).join('')}</div>`;checkAIStatus()}
function topics(){M.innerHTML=header('文法一覧','8テーマを文章読解まで練習')+`<div class="grid topics">${TOPICS.map(topicCard).join('')}</div>`}
function start(id){ses={t:topic(id),step:0,answered:false,reading:null,loading:false};renderSession()}
function renderSession(){const labels=['理解','4択','英作文','読解','完了'];M.innerHTML=header(ses.t.icon+' '+ses.t.name,ses.t.rule)+`<div class="steps">${labels.map((z,i)=>`<span class="step ${i<ses.step?'done':i===ses.step?'on':''}">${i+1}. ${z}</span>`).join('')}</div><div id="b"></div>`;if(ses.step===0)learn();else if(ses.step===1)quiz();else if(ses.step===2)write();else if(ses.step===3)read();else complete()}
function learn(){const t=ses.t;document.getElementById('b').innerHTML=`<div class="card"><div class="rule">${esc(t.rule)}</div><h3>${esc(t.example)}</h3><p class="muted">${esc(t.ja)}</p><div class="row"><button class="btn ghost" data-speak>🔊 例文</button><button class="btn primary" data-next>4択へ →</button></div></div>`}
function quiz(){const t=ses.t;document.getElementById('b').innerHTML=`<div class="card"><div class="q">${esc(t.quiz)}</div><div class="opts">${t.choices.map((o,i)=>`<button class="opt" data-q="${i}">${esc(o)}</button>`).join('')}</div><div id="f"></div></div>`}
function answerQuiz(i){if(ses.answered)return;ses.answered=true;const t=ses.t,bs=[...document.querySelectorAll('[data-q]')],ok=i===t.answer;bs[t.answer].classList.add('ok');if(!ok)bs[i].classList.add('ng');if(ok)addXp(5);else addReview(t,t.quiz,t.choices[t.answer]+' — '+t.quizExp,'bad');document.getElementById('f').innerHTML=`<div class="feed ${ok?'ok':'ng'}"><b>${ok?'正解！':'復習に追加'}</b><br>${esc(t.quizExp)}</div><button class="btn primary" data-towrite>英作文へ →</button>`}
function write(){const t=ses.t;document.getElementById('b').innerHTML=`<div class="card"><h3>日本語から英文を作る</h3><div class="q">${esc(t.writeJa)}</div><input id="a" class="input" autocomplete="off" placeholder="英文を入力"><div class="row" style="margin-top:9px"><button class="btn primary" data-check>答え合わせ</button><button class="btn ghost" data-show>答えを見る</button></div><div id="f"></div></div>`}
function normalize(s){return String(s).trim().toLowerCase().replace(/[.!?]/g,'').replace(/\s+/g,' ')}
function checkWrite(show){const t=ses.t,ok=!show&&normalize(document.getElementById('a').value)===normalize(t.writeEn);if(ok)addXp(8);else addReview(t,t.writeJa,t.writeEn,'bad');document.getElementById('f').innerHTML=`<div class="feed ${ok?'ok':'ng'}"><b>${ok?'正解！':'模範解答'}</b><br>${ok?'自力で作れています。':esc(t.writeEn)}</div><button class="btn primary" data-toread>読解へ →</button>`}
function pool(id){return [...(BUILTIN[id]||[]),...(S.aiBank[id]||[])]}
function unseen(id){const seen=new Set(S.seen[id]||[]);return pool(id).filter(p=>!seen.has(p.id))}
function markSeen(id,pid){S.seen[id]=[...(S.seen[id]||[]),pid].slice(-40);save()}
function randomItem(a){return a[Math.floor(Math.random()*a.length)]}
async function prepareReading(forceAI=false){if(ses.loading)return;ses.loading=true;const b=document.getElementById('b');if(b)b.innerHTML=`<div class="card"><span class="spinner"></span> ${forceAI?'AIで新しい短文を作成中…':'短文を準備中…'}</div>`;let p=null;if(!forceAI){const u=unseen(ses.t.id);if(u.length)p=randomItem(u)}if(!p){const bank=S.aiBank[ses.t.id]||[];if(forceAI||bank.length<8){try{p=await generateAI(ses.t.id)}catch(e){toast(e.message||'AI生成に失敗しました')}}}if(!p){S.seen[ses.t.id]=[];save();p=randomItem(pool(ses.t.id))}ses.reading=p;markSeen(ses.t.id,p.id);ses.loading=false;read()}
async function generateAI(id){const avoids=(S.aiBank[id]||[]).slice(-6).map(x=>x.title);const r=await fetch('/api/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({grammarId:id,avoidTitles:avoids})});let data={};try{data=await r.json()}catch{}if(!r.ok){if(r.status===503)throw new Error('AI生成にはVercel側のOPENAI_API_KEY設定が必要です。');throw new Error(data.error||'AI生成に失敗しました。')}const p=data.passage;if(!p||!p.id)throw new Error('AI短文の形式が正しくありません。');S.aiBank[id]=[...(S.aiBank[id]||[]),p].slice(-8);S.aiCount=(S.aiCount||0)+1;save();return p}
function read(){const b=document.getElementById('b');if(!ses.reading){prepareReading(false);return}const p=ses.reading;const source=p.source==='ai'?'<span class="badge ai">✨ AI生成・保存済み</span>':'<span class="badge">📚 固定短文</span>';b.innerHTML=`<div class="card"><div class="row" style="justify-content:space-between"><div><h2 style="margin:0">短文読解</h2><div class="muted">${esc(p.title||'Reading')}</div></div>${source}</div><p class="muted">まず普通に読み、文法を意識しすぎず内容を取る。</p><div class="pass">${esc(p.passage)}</div><div class="q">${esc(p.question)}</div><div class="opts">${p.choices.map((o,i)=>`<button class="opt" data-r="${i}">${esc(o)}</button>`).join('')}</div><div id="f"></div><div class="row" style="margin-top:14px"><button class="btn ghost" data-new-ai>✨ AIで新しい短文を追加</button><span class="muted" style="font-size:12px">このボタンではAPIを1回使用。通常は未読が尽きた時だけ自動生成</span></div></div>`}
function answerRead(i){if(ses.answered)return;ses.answered=true;const p=ses.reading,bs=[...document.querySelectorAll('[data-r]')],ok=i===p.answer;bs[p.answer].classList.add('ok');if(!ok)bs[i].classList.add('ng');if(ok)addXp(7);else addReview(ses.t,p.question,p.choices[p.answer],'bad');document.getElementById('f').innerHTML=`<div class="feed ${ok?'ok':'ng'}"><b>${ok?'正解！':'復習に追加'}</b><br>${esc(p.explanation||'')}</div><button class="btn primary" data-finish>完了</button>`}
function complete(){const t=ses.t;S.done[t.id]=(S.done[t.id]||0)+1;addXp(15);addReview(t,t.rule,t.example,'new');document.getElementById('b').innerHTML=`<div class="card" style="text-align:center"><div style="font-size:48px">🎉</div><h2>${esc(t.name)} 完了！</h2><p class="muted">次回は未読の短文が優先されます。</p><button class="btn primary" data-v="home">ホームへ</button></div>`}
function review(){const d=due();M.innerHTML=header('復習','忘却曲線ベース：思い出せたら間隔を伸ばす')+`<div class="card" style="margin-bottom:13px"><b>復習スケジュール</b><p class="muted" style="margin-bottom:0">20分 → 1日 → 3日 → 7日 → 14日 → 30日 → 60日。忘れた項目は20分後から再スタートします。</p></div><div class="card">${d.length?d.map((r,i)=>`<div class="review"><div class="row" style="justify-content:space-between;align-items:center"><b>${esc(topic(r.id)?.name||'文法')}</b><span class="muted" style="font-size:12px">現在: ${esc(scheduleLabel(reviewStage(r)))}</span></div><div class="q" style="font-size:17px">${esc(r.p)}</div><button class="btn ghost" data-rev="${i}">答え</button><div id="rv${i}" class="hidden"><div class="rule">${esc(r.a)}</div><div class="row" style="margin-top:8px"><button class="btn ghost" data-grade="bad" data-i="${i}">難しい</button><button class="btn primary" data-grade="good" data-i="${i}">思い出せた</button></div></div></div>`).join(''):'復習はありません ✅'}</div>`}
function grade(i,g){const r=due()[i],t=topic(r.id),updated=addReview(t,r.p,r.a,g);if(g==='good')addXp(5);toast(g==='good'?`次回復習：${scheduleLabel(reviewStage(updated))}後`:'20分後にもう一度復習します');review()}
function stats(){const aiSaved=Object.values(S.aiBank).reduce((n,a)=>n+(a?.length||0),0);M.innerHTML=header('学習記録','習熟度と継続を確認')+`<div class="grid g3"><div class="card stat"><small>AI生成回数</small><b>${S.aiCount||0}</b></div><div class="card stat"><small>保存済みAI短文</small><b>${aiSaved}</b></div><div class="card stat"><small>総XP</small><b>${S.xp}</b></div></div><div class="card" style="margin-top:13px">${TOPICS.map(t=>`<p>${esc(t.name)} <b>${mastery(t.id)}%</b></p><div class="bar"><i style="width:${mastery(t.id)}%"></i></div>`).join('')}</div>`}
function speak(s){if('speechSynthesis'in window){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(s);u.lang='en-US';u.rate=.88;speechSynthesis.speak(u)}}
function toast(s){const e=document.createElement('div');e.className='toast';e.textContent=s;document.body.appendChild(e);setTimeout(()=>e.remove(),3800)}
async function installApp(){if(isStandalone()){toast('すでにアプリとして起動しています。');return}if(deferredInstall){deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;home();return}if(isIOS())toast('Safariの共有ボタン →「ホーム画面に追加」を選んでください。');else toast('ブラウザメニューの「アプリをインストール」または「ホーム画面に追加」を選んでください。')}
async function checkAIStatus(){try{const r=await fetch('/api/generate',{cache:'no-store'});const d=await r.json();aiConfigured=!!d.configured}catch{aiConfigured=false}const e=document.getElementById('ai-status');if(e)e.textContent=aiConfigured?'✨ AI短文生成：利用可能':'📚 AI未設定でも固定短文で学習できます（OPENAI_API_KEY設定後にAI利用可能）'}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;if(document.querySelector('[data-install]'))home()});window.addEventListener('appinstalled',()=>{deferredInstall=null;toast('GrammarLoopをインストールしました。');home()});
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js').catch(()=>{}));
document.addEventListener('click',async e=>{const q=e.target.closest('button');if(!q)return;if(q.dataset.v)go(q.dataset.v);else if(q.dataset.start)start(q.dataset.start);else if('rec'in q.dataset){due().length?go('review'):start([...TOPICS].sort((a,b)=>mastery(a.id)-mastery(b.id))[0].id)}else if('next'in q.dataset){ses.step=1;ses.answered=false;renderSession()}else if(q.dataset.q!==undefined)answerQuiz(+q.dataset.q);else if('towrite'in q.dataset){ses.step=2;ses.answered=false;renderSession()}else if('check'in q.dataset)checkWrite(false);else if('show'in q.dataset)checkWrite(true);else if('toread'in q.dataset){ses.step=3;ses.answered=false;ses.reading=null;renderSession()}else if(q.dataset.r!==undefined)answerRead(+q.dataset.r);else if('finish'in q.dataset){ses.step=4;renderSession()}else if('speak'in q.dataset)speak(ses.t.example);else if('newAi'in q.dataset){ses.reading=null;ses.answered=false;prepareReading(true)}else if('install'in q.dataset)installApp();else if(q.dataset.rev!==undefined)document.getElementById('rv'+q.dataset.rev).classList.remove('hidden');else if(q.dataset.grade)grade(+q.dataset.i,q.dataset.grade)});
document.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target.id==='a')checkWrite(false)});home();
